"""expenses

Revision ID: 178d25beb803
Revises: b7f3c1a9d2e4
Create Date: 2026-07-07 12:52:37.594859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178d25beb803'
down_revision = 'b7f3c1a9d2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=True),
    sa.Column('thumb_key', sa.String(length=255), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_is_handwritten', sa.Boolean(), nullable=True),
    sa.Column('amount_parse_ok', sa.Boolean(), nullable=True),
    sa.Column('is_modified_by_user', sa.Boolean(), nullable=False),
    sa.Column('ocr_raw', sa.JSON(), nullable=True),
    sa.Column('no_receipt_reason', sa.Text(), nullable=True),
    sa.Column('doc_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['doc_types.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_created_by'), ['created_by'], unique=False)
        batch_op.create_index('ix_expenses_created_by_status', ['created_by', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_status'), ['status'], unique=False)
        batch_op.create_index('ix_expenses_store_bizdate', ['store_id', 'business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_expenses_store_status', ['store_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_store_status')
        batch_op.drop_index(batch_op.f('ix_expenses_store_id'))
        batch_op.drop_index('ix_expenses_store_bizdate')
        batch_op.drop_index(batch_op.f('ix_expenses_status'))
        batch_op.drop_index('ix_expenses_created_by_status')
        batch_op.drop_index(batch_op.f('ix_expenses_created_by'))

    op.drop_table('expenses')
    # ### end Alembic commands ###
