"""accounting_periods + expenses.period_id

Revision ID: 351cd5d6a353
Revises: 7a3b5764ae78
Create Date: 2026-07-15 11:52:10.486819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351cd5d6a353'
down_revision = '7a3b5764ae78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('lock_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_periods_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_periods_start_date'), ['start_date'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_period_id'), ['period_id'], unique=False)
        batch_op.create_foreign_key('fk_expenses_period_id_accounting_periods', 'accounting_periods', ['period_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_period_id_accounting_periods', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_period_id'))
        batch_op.drop_column('period_id')

    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_periods_start_date'))
        batch_op.drop_index(batch_op.f('ix_accounting_periods_end_date'))

    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
