"""audit: handovers + audit_log + expense audit fields

Revision ID: 37473b75d466
Revises: 178d25beb803
Create Date: 2026-07-08 10:12:33.084999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37473b75d466'
down_revision = '178d25beb803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handovers_store_id'), ['store_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_expense_id'), ['expense_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audited_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('audited_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_modified_by_manager', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('handover_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_handover_id'), ['handover_id'], unique=False)
        batch_op.create_foreign_key('fk_expenses_audited_by_users', 'users', ['audited_by'], ['id'])
        batch_op.create_foreign_key('fk_expenses_handover_id_handovers', 'handovers', ['handover_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_handover_id_handovers', type_='foreignkey')
        batch_op.drop_constraint('fk_expenses_audited_by_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_handover_id'))
        batch_op.drop_column('handover_id')
        batch_op.drop_column('is_modified_by_manager')
        batch_op.drop_column('audited_at')
        batch_op.drop_column('audited_by')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_expense_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handovers_store_id'))

    op.drop_table('handovers')
    # ### end Alembic commands ###
