"""ocr: expenses.ocr_scheduled_at reschedule throttle

Revision ID: 68b03ba4051f
Revises: a5f235aa0069
Create Date: 2026-07-08 14:08:24.173671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b03ba4051f'
down_revision = 'a5f235aa0069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_scheduled_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('ocr_scheduled_at')

    # ### end Alembic commands ###
