"""expenses reconcile fields

Revision ID: 99c5ab162dc6
Revises: a7c3e9f1d5b8
Create Date: 2026-07-13 16:53:30.419908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c5ab162dc6'
down_revision = 'a7c3e9f1d5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconciled_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key('fk_expenses_reconciled_by_users', 'users', ['reconciled_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_reconciled_by_users', type_='foreignkey')
        batch_op.drop_column('note')
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('reconciled_at')
        batch_op.drop_column('reconciled_by')

    # ### end Alembic commands ###
