"""ocr: ocr_log table + expenses ocr_failed fields

Revision ID: a5f235aa0069
Revises: 37473b75d466
Create Date: 2026-07-08 13:11:51.571280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f235aa0069'
down_revision = '37473b75d466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('error_type', sa.String(length=16), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_log_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocr_log_store_id'), ['store_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('ocr_failed', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('ocr_last_error', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('ocr_last_error')
        batch_op.drop_column('ocr_failed')
        batch_op.drop_column('ocr_attempts')

    with op.batch_alter_table('ocr_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_log_store_id'))
        batch_op.drop_index(batch_op.f('ix_ocr_log_expense_id'))

    op.drop_table('ocr_log')
    # ### end Alembic commands ###
