"""doc_types

Revision ID: f2f9cc2cd83c
Revises: 9c5e2633ea5f
Create Date: 2026-07-02 09:41:53.812595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f9cc2cd83c'
down_revision = '9c5e2633ea5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('physical_return_required', sa.Boolean(), nullable=False),
    sa.Column('purge_policy', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_types')
    # ### end Alembic commands ###
